### ISSUE TITLE
Linguagem Rust vs C/C++

### ISSUE THREAD

**Issue by pauloteixeira01** [naomijub/livro-rust#1]
Estou ouvindo muito falar que essa linguagem substituirá o C/C++. 
Motivo: Administrar melhor a memória.
Alguém poderia explicar?

**Comment by naomijub** [comment]
Rust é uma linguagem de sistemas desenvolvida inicialmente pela Mozilla para substituir, especialmente, C++ no Firefox.

**Comment by naomijub** [comment]
A partir da sintaxe mais clara e da segurança de memória, muitas outras aplicações surgiram para tirar proveito dessa performance, como games e web.

**Comment by naomijub** [comment]
Existe também o uso com webassembly https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm que pelos meus testes melhorou muito a performance em relação ao js puro

**Comment by pauloteixeira01** [comment]
> A partir da sintaxe mais clara e da segurança de memória, muitas outras aplicações surgiram para tirar proveito dessa performance, como games e web.

Essa linguagem tem a mesma performance do C++?
Sou fã da Mozilla mas, acho essa idéia muito arriscada.

**Comment by naomijub** [comment]
É muito semelhante, varia de caso a caso, mas bastante próxima. 
Já é uma linguagem com 7 anos, não é arriscado. A dificuldade é migrar todo codigo C/C++ para rust
Alguns comparativos:
https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust.html
https://www.bitdegree.org/tutorials/rust-vs-cpp/

**Comment by pauloteixeira01** [comment]
> É muito semelhante, varia de caso a caso, mas bastante próxima.
> Já é uma linguagem com 7 anos, não é arriscado. A dificuldade é migrar todo codigo C/C++ para rust
> Alguns comparativos:
> https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust.html
> https://www.bitdegree.org/tutorials/rust-vs-cpp/

Muito Bom então...Bola pra frente.

**Comment by pauloteixeira01** [comment]
A linguagem Rust consegue controlar o hardware como o C faz?

**Comment by naomijub** [comment]
https://www.google.com/search?q=can+rust+control+hardware&oq=can+rust+control+hardware&aqs=chrome..69i57.6386j0j4&sourceid=chrome&ie=UTF-8

**Comment by pauloteixeira01** [comment]
> https://www.google.com/search?q=can+rust+control+hardware&oq=can+rust+control+hardware&aqs=chrome..69i57.6386j0j4&sourceid=chrome&ie=UTF-8

Show. Realmente, é muito interessante.

**Comment by pauloteixeira01** [comment]
@eagle-head
